language: r
sudo: false
cache: packages

r_github_packages:
  - berndbischl/BBmisc
  - jimhester/lintr

warnings_are_errors: false

install:
  - Rscript -e 'if (length(find.package("devtools", quiet = TRUE)) == 0) install.packages("devtools")'
