language: r
sudo: false
cache: packages

r_github_packages:
  - berndbischl/BBmisc
  - jimhester/lintr

warnings_are_errors: false

install:
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
